"""Generate the numeric sections of a Harbor-run benchmark manifest from its
committed results.json, so every count has one source (maturity plan T1.6).

Usage:
    python3 bench/tb20_manifest.py docs/benchmarks/2026-08-25-tb20/results.json

Prints a markdown block; the manifest embeds it between GENERATED markers via
--write <manifest.md>. Classification rules are the ones the manifest's prose
already used; they now live here and nowhere else.
"""

import argparse
import json
from pathlib import Path


def classify(trial: dict) -> str:
    if trial.get("reward") is not None and trial["reward"] >= 1:
        return "solved"
    if trial.get("stopStatus") == "budget_exceeded":
        return "ceiling_stop"
    error = trial.get("error") or ""
    if "timed out" in error:
        return "timeout"
    if "Docker" in error or "exit 1" in error:
        return "infrastructure"
    if error:
        return "other_error"
    return "scored_failure"


def render(results: dict) -> str:
    trials = results["trials"]
    classes = {}
    for trial in trials:
        classes.setdefault(classify(trial), []).append(trial)
    solved = classes.get("solved", [])
    solved_capped = [t for t in solved if t.get("stopStatus") == "budget_exceeded"]
    priced = [t for t in trials if t.get("costUSD") is not None]
    spend = sum(t["costUSD"] for t in priced)
    n = len(trials)

    def row(label, key, attribution):
        return f"| {label} | {len(classes.get(key, []))} | {attribution} |"

    lines = [
        "<!-- GENERATED by bench/tb20_manifest.py from results.json; do not edit by hand -->",
        f"HEADLINE (ADR 0017 fitness function): ${spend/len(solved):.3f} measured spend per solve; "
        f"{len(solved)}/{n} solved ({len(solved)/n*100:.1f}%); ${spend:.2f} measured across {len(priced)} priced trials.",
        f"Trials: {n}. Solved: {len(solved)}/{n} ({len(solved)/n*100:.1f}%).",
        f"Measured spend: ${spend:.2f} across {len(priced)} priced trials "
        f"({n - len(priced)} unpriced, so true spend is higher).",
        f"Total measured spend per solve: ${spend/len(solved):.3f} (subtotal over priced trials, not a rate).",
        f"Ceiling stops in all: {len(classes.get('ceiling_stop', [])) + len(solved_capped)} "
        f"({len(classes.get('ceiling_stop', []))} unsolved, {len(solved_capped)} solved while being cut off).",
        "",
        "| Class | Count | Attribution |",
        "|---|---|---|",
        row("Solved", "solved", "outcome"),
        row("Scored but failed", "scored_failure", "capability"),
        row("Stopped by the per-trial spend cap (unsolved)", "ceiling_stop", "cost-bounding choice; counterfactual unknown"),
        row("Agent or verifier timeout", "timeout", "time-bounding choice; counterfactual unknown"),
        row("Docker / install / other harness failures", "infrastructure", "local infrastructure; counterfactual unknown"),
        row("Other errors", "other_error", "unclassified"),
        "",
        "Cost distributions (priced trials only):",
        "",
        "| Class | n priced | min | median | max |",
        "|---|---|---|---|---|",
        dist("Solved", solved),
        dist("Ceiling-stopped (incl. solved-while-capped)", classes.get("ceiling_stop", []) + solved_capped),
        dist("Scored failures", classes.get("scored_failure", [])),
        "<!-- END GENERATED -->",
    ]
    return "\n".join(lines)


def dist(label: str, trials: list) -> str:
    costs = sorted(t["costUSD"] for t in trials if t.get("costUSD") is not None)
    if not costs:
        return f"| {label} | 0 | - | - | - |"
    return f"| {label} | {len(costs)} | ${costs[0]:.3f} | ${costs[len(costs)//2]:.3f} | ${costs[-1]:.3f} |"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results", type=Path)
    parser.add_argument("--write", type=Path, help="manifest to splice the block into")
    parser.add_argument("--check", type=Path, help="manifest whose generated block must equal a fresh render (CI)")
    args = parser.parse_args()
    block = render(json.loads(args.results.read_text()))
    if args.check:
        text = args.check.read_text()
        start, end = "<!-- GENERATED", "<!-- END GENERATED -->"
        if start not in text or end not in text:
            raise SystemExit(f"{args.check}: no generated block; run --write first")
        current = text[text.index(start): text.index(end) + len(end)]
        if current != block:
            raise SystemExit(f"{args.check}: generated block is stale relative to {args.results}; rerun --write")
        print(f"{args.check}: generated block matches results.json")
        return 0
    if not args.write:
        print(block)
        return 0
    text = args.write.read_text()
    start, end = "<!-- GENERATED", "<!-- END GENERATED -->"
    if start in text and end in text:
        head = text[: text.index(start)]
        tail = text[text.index(end) + len(end):]
        text = head + block + tail
    else:
        marker = "## Score, honestly accounted"
        if marker not in text:
            raise SystemExit("manifest has neither GENERATED markers nor the score section")
        text = text.replace(marker, marker + "\n\n" + block + "\n", 1)
    args.write.write_text(text)
    print(f"spliced generated block into {args.write}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
