#!/usr/bin/env node
/**
 * Syncs curated praxis assets into .agent/skills so upstream praxis changes flow
 * without manual copying. The MAPPINGS table below is the curation decision:
 * what we take, where it lands, and the one-line summary piko's skill index shows.
 *
 * Usage:
 *   node scripts/sync-praxis.mjs            # sync from $PRAXIS_DIR or a cached clone
 *   node scripts/sync-praxis.mjs --check    # exit 1 if targets drift from upstream
 *
 * Praxis source: https://github.com/jeet129/praxis (MIT). Local-only skills
 * (kind: "local") are never touched by sync.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const PRAXIS_REPO = 'https://github.com/jeet129/praxis';
const SKILLS_DIR = new URL('../.agent/skills/', import.meta.url).pathname;

const MAPPINGS = [
  {
    target: 'code-review.md',
    source: 'skills/code-review/SKILL.md',
    summary:
      'Code review discipline: severity-ranked findings, anti-rationalization checks, verify before approving',
  },
  {
    target: 'definition-of-done.md',
    source: 'skills/definition-of-done/SKILL.md',
    summary:
      'Definition of done: a change is complete only when tested, verified, documented, and its checklist passes',
  },
  {
    target: 'adr-decision-records.md',
    source: 'skills/adr-decision-records/SKILL.md',
    summary: 'ADR practice: record every architectural decision in docs/adr with context, options, and consequences',
  },
  {
    target: 'codebase-comprehension.md',
    source: 'skills/codebase-comprehension/SKILL.md',
    summary:
      'Codebase comprehension: map, then read call paths, then confirm behavior with running code before changing it',
  },
  {
    target: 'security-review.md',
    source: 'agents/security-reviewer.md',
    summary:
      'Security review: trust boundaries, secret exposure, injection paths, containment escapes; assume hostile inputs',
  },
  // Originals maintained in this repo; sync never touches them.
  { target: 'release-checklist.md', kind: 'local' },
];

function resolvePraxisDir() {
  const configured = process.env.PRAXIS_DIR;
  if (configured) {
    if (!existsSync(join(configured, 'plugin.json'))) {
      throw new Error(`PRAXIS_DIR does not look like a praxis checkout: ${configured}`);
    }
    return configured;
  }
  const cache = join(homedir(), '.cache', 'piko', 'praxis');
  if (existsSync(join(cache, '.git'))) {
    try {
      execFileSync('git', ['-C', cache, 'pull', '--ff-only', '--quiet'], { stdio: 'inherit' });
    } catch {
      console.warn('warning: could not update the cached praxis clone; syncing from its current state');
    }
  } else {
    mkdirSync(cache, { recursive: true });
    execFileSync('git', ['clone', '--depth', '1', PRAXIS_REPO, cache], { stdio: 'inherit' });
  }
  return cache;
}

function upstreamCommit(dir) {
  try {
    return execFileSync('git', ['-C', dir, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

function render(mapping, praxisDir, commit) {
  const body = readFileSync(join(praxisDir, mapping.source), 'utf8');
  const withoutTitle = body.split('\n').slice(1).join('\n').replace(/^\n+/, '');
  return `# ${mapping.summary}

> Synced from praxis ${mapping.source} @ ${commit} (${PRAXIS_REPO}, MIT) by
> scripts/sync-praxis.mjs. Do not edit this file; change the summary in the
> script or the content upstream, then re-sync.

${withoutTitle}`;
}

const checkOnly = process.argv.includes('--check');
const praxisDir = resolvePraxisDir();
const commit = upstreamCommit(praxisDir);
let drifted = 0;
let synced = 0;

for (const mapping of MAPPINGS) {
  if (mapping.kind === 'local') continue;
  const targetPath = join(SKILLS_DIR, mapping.target);
  const next = render(mapping, praxisDir, commit);
  const current = existsSync(targetPath) ? readFileSync(targetPath, 'utf8') : '';
  if (current === next) continue;
  if (checkOnly) {
    console.error(`drift: ${mapping.target} differs from praxis@${commit} ${mapping.source}`);
    drifted++;
  } else {
    writeFileSync(targetPath, next, 'utf8');
    console.log(`synced: ${mapping.target} <- ${mapping.source} @ ${commit}`);
    synced++;
  }
}

if (checkOnly && drifted > 0) process.exit(1);
console.log(checkOnly ? 'no drift' : `done (${synced} file${synced === 1 ? '' : 's'} updated, praxis @ ${commit})`);
